Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
